name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

    - name: Log in to IBM Container Registry
      env:
        IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
      run: |
        ibmcloud login --apikey $IBM_CLOUD_API_KEY -r jp-tok
        ibmcloud plugin install container-registry
        ibmcloud cr region-set global
        ibmcloud cr login


    - name: Build Docker image
      run: |
        docker build -t icr.io/client-engineering/visual-gpt:latest .

    - name: Push Docker image to IBM Container Registry
      run: |
        docker push icr.io/client-engineering/visual-gpt:latest